### ISSUE TITLE
Ability to ignore some links/references

### ISSUE THREAD

**Issue by jooola** [ory/closed-reference-notifier#83]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/closed-reference-notifier/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/closed-reference-notifier/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

From what I understand in the docs, we can ignore files using paths in a `.reference-ignore` file or directly using the `.ignore` input field filled wiht paths.

I would like to be able to ignore some issue links that should not raise a new reference closed issues.

### Describe your ideal solution

I don't know what the best way is to do this, but either using a list of urls, or by placing a comment near the link in the code ?

The comment in the code seem really verbose, so maybe a list of urls is a better idea. Passing it through a github action field input could be a good thing ?

### Workarounds or alternatives

None

### Version

v1.3.3

**Comment by zepatrik** [comment]
I am very sorry for the late response, somehow missed the notification.
Your use case is definitely a good idea, I actually had the same problem already myself. I think it makes sense to add something to the comment itself. You might reference one issue on purpose somewhere, but maybe you would like to be notified elsewhere. Also, managing a separate file seems like to much work for me, if you could just add an exclamation mark (or similar) before the link in the comment.

**Comment by jooola** [comment]
Awesome ! Thanks !

**Comment by zepatrik** [comment]
You're welcome :wink:
